# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIrctc2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_irctc2(self):
    self.driver.get("https://www.irctc.co.in/nget/train-search")
    self.driver.set_window_size(1440, 900)
    self.driver.find_element(By.LINK_TEXT, "LOGIN").click()
    self.driver.find_element(By.ID, "8991699").send_keys("Amanjham1")
    element = self.driver.find_element(By.CSS_SELECTOR, "span > .search_btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "disha-banner-close").click()
    self.driver.find_element(By.ID, "nlpAnswer").click()
    self.driver.find_element(By.ID, "nlpAnswer").click()
    self.driver.find_element(By.ID, "nlpAnswer").send_keys("fqtl")
    self.driver.find_element(By.CSS_SELECTOR, "span > .search_btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").send_keys("alwa")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").click()
    self.driver.find_element(By.CSS_SELECTOR, "#p-highlighted-option > .ng-star-inserted").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-datepicker-next-icon").click()
    self.driver.find_element(By.LINK_TEXT, "5").click()
    self.driver.find_element(By.CSS_SELECTOR, "#journeyQuota > .ng-tns-c65-12").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-state-highlight").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dropdown-label-container > .ng-tns-c65-11").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-swap:nth-child(3) > .col-md-7").click()
    self.driver.find_element(By.CSS_SELECTOR, ".train_Search").click()
    self.driver.execute_script("window.scrollTo(0,1159)")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(8) .col-sm-5 > strong").click()
  
