# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMmt():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mmt(self):
    self.driver.get("https://www.makemytrip.com/")
    self.driver.set_window_size(1440, 900)
    element = self.driver.find_element(By.CSS_SELECTOR, ".chHolidays")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".chTrains").click()
    element = self.driver.find_element(By.ID, "fromCity")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".react-autosuggest__input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".activeWidget").click()
    self.driver.find_element(By.CSS_SELECTOR, "#react-autowhatever-1-section-0-item-0 p:nth-child(2) > .sr_city").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-autosuggest__input").send_keys("gand")
    self.driver.find_element(By.CSS_SELECTOR, "#react-autowhatever-1-section-0-item-1 .searchedResult > .sr_city").click()
    self.driver.find_element(By.CSS_SELECTOR, ".DayPicker-Day--selected").click()
    self.driver.find_element(By.CSS_SELECTOR, ".travelForPopup > li:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".primaryBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".single-train-detail:nth-child(5) .flex-column:nth-child(1) > .card > .flex:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".trdDataTuple:nth-child(1) .checkBox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkboxListItem:nth-child(2) > .hrtlCenter .font14").click()
    self.driver.find_element(By.CSS_SELECTOR, ".paymentBtn > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hrtlCenter > .radioBox > .darkGreyText").click()
    self.driver.find_element(By.CSS_SELECTOR, ".paymentBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkboxListItem:nth-child(1) .checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".paymentBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".leftSection").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkboxListItem:nth-child(2) .radioBox > .darkGreyText").click()
    self.driver.find_element(By.CSS_SELECTOR, ".getFc__list--item:nth-child(2) .font14").click()
    self.driver.find_element(By.CSS_SELECTOR, ".paymentBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".box-padding:nth-child(2) > .payment__option__title").click()
    self.driver.find_element(By.ID, "inputVpa").click()
    self.driver.find_element(By.ID, "inputVpa").send_keys("911")
  
