# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestYatra():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_yatra(self):
    self.driver.get("https://www.yatra.com/")
    self.driver.set_window_size(1846, 1053)
    self.driver.find_element(By.CSS_SELECTOR, ".more-arr").click()
    self.driver.find_element(By.CSS_SELECTOR, "#booking_engine_trains > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".icon-gift_voucher")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "booking_engine_gift_voucher")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "booking_engine_gift_voucher")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "BE_train_from_station").click()
    self.driver.find_element(By.ID, "BE_train_from_station").send_keys("del")
    element = self.driver.find_element(By.CSS_SELECTOR, ".show-depart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".train-info-block:nth-child(2) > .relundefinedSL > p").click()
    self.driver.find_element(By.ID, "trainquota22").click()
    self.driver.find_element(By.ID, "bookBtn2").click()
    self.driver.find_element(By.ID, "bookNowBtn").click()
  
