# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIrctc():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_irctc(self):
    self.driver.get("https://www.irctc.co.in/nget/train-search")
    self.driver.set_window_size(1846, 1053)
    self.driver.find_element(By.LINK_TEXT, "LOGIN").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ui-inputgroup-addon strong")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "950037").send_keys("pjay20301")
    self.driver.find_element(By.ID, "5733518").click()
    self.driver.find_element(By.ID, "5733518").send_keys("Password1")
    self.driver.find_element(By.ID, "nlpAnswer").click()
    self.driver.find_element(By.ID, "nlpAnswer").send_keys("SAIL SEQR")
    self.driver.find_element(By.CSS_SELECTOR, "span > .search_btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").send_keys("panj")
    self.driver.find_element(By.CSS_SELECTOR, "#p-highlighted-option > .ng-star-inserted").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-9 > .ui-inputtext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-9 > .ui-inputtext").send_keys("hy")
    self.driver.find_element(By.CSS_SELECTOR, "#p-highlighted-option > .ng-tns-c57-9").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c58-10 > .ui-inputtext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(2) > .ng-tns-c58-10:nth-child(5)").click()
    self.driver.find_element(By.LINK_TEXT, "22").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c65-11 > .ui-dropdown-trigger-icon").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c65-11:nth-child(6) > .ui-dropdown-item").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c65-12 > .ui-dropdown-trigger-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c65-12:nth-child(3) > .ui-dropdown-item").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-button-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(4) > .css-label_c").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-confirmdialog-acceptbutton > .ui-button-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".train_Search").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-widget-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-confirmdialog-rejectbutton > .ui-button-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").send_keys("del")
    self.driver.find_element(By.ID, "p-highlighted-option").click()
    self.driver.find_element(By.CSS_SELECTOR, ".train_Search").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".train_Search")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-8 > .ui-inputtext").send_keys("delhi")
    self.driver.find_element(By.ID, "p-highlighted-option").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-9 > .ui-inputtext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c57-9 > .ui-inputtext").send_keys("hyde")
    self.driver.find_element(By.CSS_SELECTOR, "#p-highlighted-option > .ng-tns-c57-9").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c58-10 > .ui-inputtext").click()
    self.driver.find_element(By.LINK_TEXT, "22").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dropdown-label-container > .ng-tns-c65-11").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c65-11:nth-child(6) .ng-star-inserted").click()
    self.driver.find_element(By.CSS_SELECTOR, "#journeyQuota > .ng-tns-c65-12").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c65-12:nth-child(3) > .ui-dropdown-item").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-button-icon-left").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(4) > .css-label_c").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-confirmdialog-acceptbutton > .ui-button-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".train_Search").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(1) .btnDefault:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
