# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestYatra():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_yatra(self):
    self.driver.get("https://www.yatra.com/")
    self.driver.set_window_size(1440, 900)
    self.driver.find_element(By.CSS_SELECTOR, ".type-active").click()
    self.driver.find_element(By.ID, "BE_flight_origin_city").click()
    self.driver.find_element(By.ID, "BE_flight_origin_city").send_keys("jai")
    self.driver.find_element(By.CSS_SELECTOR, ".active .ac_cityname").click()
    self.driver.find_element(By.ID, "BE_flight_arrival_city").send_keys("hyd")
    self.driver.find_element(By.CSS_SELECTOR, ".active .ac_airportname").click()
    self.driver.find_element(By.ID, "BE_flight_origin_date").click()
    self.driver.find_element(By.ID, "05/12/2022").click()
    self.driver.find_element(By.ID, "BE_flight_flsearch_btn").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,109)")
    self.driver.execute_script("window.scrollTo(0,226)")
    self.driver.find_element(By.CSS_SELECTOR, "#JAIHYDI51229EP20221205_AIRASIAAPI .fs-14").click()
    self.driver.find_element(By.CSS_SELECTOR, "#fare-JAIHYDI51229EP20221205_AIRASIAAPI .ml-10").click()
    self.driver.execute_script("window.scrollTo(0,1)")
    self.driver.execute_script("window.scrollTo(0,132)")
    self.driver.find_element(By.CSS_SELECTOR, ".mt-1:nth-child(1) .ico").click()
    self.driver.find_element(By.ID, "travellerf0").click()
    self.driver.find_element(By.ID, "travellerf0").send_keys("Aman")
    self.driver.find_element(By.ID, "travellerl0").click()
    self.driver.find_element(By.ID, "travellerf0").click()
    self.driver.find_element(By.ID, "travellerf0").send_keys("Rajnish")
    self.driver.find_element(By.ID, "travellerl0").click()
    self.driver.find_element(By.ID, "travellerl0").send_keys("Kumar")
    self.driver.find_element(By.ID, "Adult_1_dob").click()
    element = self.driver.find_element(By.ID, "Adult_1_dob")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".datepicker-wrapper:nth-child(4) .years").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".select > .ng-dirty")
    dropdown.find_element(By.XPATH, "//option[. = '1970']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".day-block:nth-child(10) > .full > .full").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pax-proceed-btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".pax-proceed-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".mt-1:nth-child(8) .my-radio").click()
    self.driver.find_element(By.ID, "title0").click()
    dropdown = self.driver.find_element(By.ID, "title0")
    dropdown.find_element(By.XPATH, "//option[. = 'Mr.']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex-center").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(3) > .grey-btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(3) > .grey-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "gtm_saveflightreview").click()
    self.driver.find_element(By.CSS_SELECTOR, ".remove").click()
    self.driver.execute_script("window.scrollTo(0,462)")
    self.driver.execute_script("window.scrollTo(0,35)")
    self.driver.execute_script("window.scrollTo(0,44)")
  
